### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by liuzhiping138** [DirectoryLister/DirectoryLister#244]
```
Fatal error: Uncaught Error: Call to undefined function App\Controllers\mime_content_type() in /home/wwwroot/demo1.****.com/app/Controllers/DirectoryController.php:117 Stack trace:
#0 /home/wwwroot/demo1.****.com/vendor/symfony/finder/Iterator/CustomFilterIterator.php(54): App\Controllers\DirectoryController->App\Controllers\{closure}(Object(Symfony\Component\Finder\SplFileInfo))
#1 [internal function]: Symfony\Component\Finder\Iterator\CustomFilterIterator->accept()
#2 [internal function]: FilterIterator->rewind()
#3 [internal function]: FilterIterator->rewind()
#4 /home/wwwroot/demo1.****.com/vendor/symfony/finder/Iterator/SortableIterator.php(91): iterator_to_array(Object(Symfony\Component\Finder\Iterator\PathFilterIterator), true)
#5 /home/wwwroot/demo1.****.com/vendor/symfony/finder/Finder.php(772): Symfony\Component\Finder\Iterator\SortableIterator->getIterator()
#6 /home/wwwroot/demo1.****.com/vendor/symfony/finder/Finder.php(614): Symfony\Component\Finder\Finder->searchInDirectory('.')
#7 /home/wwwroot/d in /home/wwwroot/demo1.****.com/app/Controllers/DirectoryController.php on line 117
```

**Comment by PHLAK** [comment]
Thanks for the feedback. Can I get some additional information to help troubleshoot?

**What version of PHP do you have installed?**

You can run `php --version` on the command line to find out.

**What HTTP server are you using to serve Directory Lister?**

e.g Apache, NGINX, etc...

Are you able to provide any error logs with more information?

**Comment by PHLAK** [comment]
Additionally, please run `php -m` and paste the output here.

**Comment by raptor76** [comment]
I had the same issue

I enabled  `fileinfo extension` and every thing is ok now

**Comment by PHLAK** [comment]
Thanks @raptor76. Closing this for now.

**Comment by Giorgi1997** [comment]
> @PHLAK
> 
> I had the same issue
> 
> I enabled `fileinfo extension` and every thing is ok now

How did you enabled   `fileinfo extension`
